[workspace]
resolver = "2"
members = [
    "k256",
    "p256",
]

[patch.crates-io]
ecdsa = { git = "https://github.com/RustCrypto/signatures.git" }
elliptic-curve = { git = "https://github.com/RustCrypto/traits.git" }
